name: Publish 
on: [ push ]
jobs:
  release:
    name: Publish release binary for kernel-paniks-orchestrator
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Publish]') || github.event_name == 'workflow_dispatch'"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout site branch
        uses: actions/checkout@v4
        with:
          ref: site
          path: site

      - name: Build
        run: nix build -L

      - name: Get version from Cargo.toml
        id: version
        uses: dante-signal31/rust-app-version@v1.2.0

      - name: Update site
        run: |
          mkdir -p site/augustomegener || true          
          mkdir -p site/augustomegener/kernel-paniks-orchestrator || true          
          mkdir -p site/augustomegener/kernel-paniks-orchestrator/${{ steps.version.outputs.app_version }}
          cp -r result/bin/kernel-paniks-orchestrator site/augustomegener/kernel-paniks-orchestrator/${{ steps.version.outputs.app_version }}/kernel-paniks-orchestrator-${{ steps.version.outputs.app_version }}
          cd ./site
          git config user.name "augustomegener"
          git config user.email "76854495+AugustoMegener@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "Update site" && git push)
